service: music-gen-service
app: music-gen-app
org: harrypankiv

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Scan"
      Resource: "arn:aws:dynamodb:us-east-1:225558997672:table/project"

plugins:
  - serverless-webpack
  # - serverless-dynamodb-local
  - serverless-offline

webpack:
  webpackConfig: ./webpack.config.js
  includeModules: true

custom:
  serverless-offline:
    httpPort: 7000
    stageVariables:
  # dynamodb:
  #   stages:
  #     - dev

functions:
  getGeneratedAudio:
    handler: src/functions/getGeneratedAudio.getGeneratedAudio
    events:
      - http:
          path: getGeneratedAudio
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                projectId: true

  generateAudio:
    handler: src/functions/generateAudio.generateAudio
    events:
      - http:
          path: generateAudio
          method: post
          cors: true
  
  exportMidi:
    handler: src/functions/exportMidi.exportMidi
    events:
      - http:
          path: exportMidi
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                projectId: true

# resources:
#   Resources:
#     project:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: project
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
